/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `/../components/FormField`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(questions)'}/CodeEntry` | `/CodeEntry`; params?: Router.UnknownInputParams; } | { pathname: `${'/(questions)'}/LoadingScreen` | `/LoadingScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(questions)'}/Onboard` | `/Onboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(questions)'}/OnboardQuestionnaire` | `/OnboardQuestionnaire`; params?: Router.UnknownInputParams; } | { pathname: `${'/(questions)'}/PreQuestionnaire` | `/PreQuestionnaire`; params?: Router.UnknownInputParams; } | { pathname: `${'/(questions)'}/questionnaire` | `/questionnaire`; params?: Router.UnknownInputParams; } | { pathname: `${'/(questions)'}/VideoFile` | `/VideoFile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(root)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/FormField`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(questions)'}/CodeEntry` | `/CodeEntry`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(questions)'}/LoadingScreen` | `/LoadingScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(questions)'}/Onboard` | `/Onboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(questions)'}/OnboardQuestionnaire` | `/OnboardQuestionnaire`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(questions)'}/PreQuestionnaire` | `/PreQuestionnaire`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(questions)'}/questionnaire` | `/questionnaire`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(questions)'}/VideoFile` | `/VideoFile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `${'/(root)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(root)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `/../components/FormField${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(questions)'}/CodeEntry${`?${string}` | `#${string}` | ''}` | `/CodeEntry${`?${string}` | `#${string}` | ''}` | `${'/(questions)'}/LoadingScreen${`?${string}` | `#${string}` | ''}` | `/LoadingScreen${`?${string}` | `#${string}` | ''}` | `${'/(questions)'}/Onboard${`?${string}` | `#${string}` | ''}` | `/Onboard${`?${string}` | `#${string}` | ''}` | `${'/(questions)'}/OnboardQuestionnaire${`?${string}` | `#${string}` | ''}` | `/OnboardQuestionnaire${`?${string}` | `#${string}` | ''}` | `${'/(questions)'}/PreQuestionnaire${`?${string}` | `#${string}` | ''}` | `/PreQuestionnaire${`?${string}` | `#${string}` | ''}` | `${'/(questions)'}/questionnaire${`?${string}` | `#${string}` | ''}` | `/questionnaire${`?${string}` | `#${string}` | ''}` | `${'/(questions)'}/VideoFile${`?${string}` | `#${string}` | ''}` | `/VideoFile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(root)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `/../components/FormField`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(questions)'}/CodeEntry` | `/CodeEntry`; params?: Router.UnknownInputParams; } | { pathname: `${'/(questions)'}/LoadingScreen` | `/LoadingScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(questions)'}/Onboard` | `/Onboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(questions)'}/OnboardQuestionnaire` | `/OnboardQuestionnaire`; params?: Router.UnknownInputParams; } | { pathname: `${'/(questions)'}/PreQuestionnaire` | `/PreQuestionnaire`; params?: Router.UnknownInputParams; } | { pathname: `${'/(questions)'}/questionnaire` | `/questionnaire`; params?: Router.UnknownInputParams; } | { pathname: `${'/(questions)'}/VideoFile` | `/VideoFile`; params?: Router.UnknownInputParams; };
    }
  }
}
